In [5]:
import pandas as pd

# Membaca data dari file CSV
file_path = 'Transjakarta.csv'
df_raw = pd.read_csv(file_path)
df_raw

,transID,payCardID,payCardBank,payCardName,payCardSex,payCardBirthDate,corridorID,corridorName,direction,tapInStops,...,tapInStopsLon,stopStartSeq,tapInTime,tapOutStops,tapOutStopsName,tapOutStopsLat,tapOutStopsLon,stopEndSeq,tapOutTime,payAmount
0,EIIW227B8L34VB,180062659848800,emoney,Bajragin Usada,M,2008,5,Matraman Baru - Ancol,1.0,P00142,...,106.84402,7,2023-04-03 05:21:44,P00253,Tegalan,-6.203101,106.85715,12.0,2023-04-03 06:00:53,3500.0
1,LGXO740D2N47GZ,4885331907664776,dki,Gandi Widodo,F,1997,6C,Stasiun Tebet - Karet via Patra Kuningan,0.0,B01963P,...,106.83302,13,2023-04-03 05:42:44,B03307P,Sampoerna Strategic,-6.217152,106.81892,21.0,2023-04-03 06:40:01,3500.0
2,DJWR385V2U57TO,4996225095064169,dki,Emong Wastuti,F,1992,R1A,Pantai Maju - Kota,0.0,B00499P,...,106.81435,38,2023-04-03 05:59:06,B04962P,Simpang Kunir Kemukus,-6.133731,106.81475,39.0,2023-04-03 06:50:55,3500.0
3,JTUZ800U7C86EH,639099174703,flazz,Surya Wacana,F,1978,11D,Pulo Gebang - Pulo Gadung 2 via PIK,0.0,B05587P,...,106.93526,23,2023-04-03 05:44:51,B03090P,Raya Penggilingan,-6.183068,106.93194,29.0,2023-04-03 06:28:16,3500.0
4,VMLO535V7F95NJ,570928206772,flazz,Embuh Mardhiyah,M,1982,12,Tanjung Priok - Pluit,0.0,P00239,...,106.88900,5,2023-04-03 06:17:35,P00098,Kali Besar Barat,-6.135355,106.81143,15.0,2023-04-03 06:57:03,3500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37895,ZWEC949B8Q87QG,4685818286724028395,brizzi,Kamila Mahendra,F,2004,6B,Ragunan - MH Thamrin via Semanggi,1.0,P00261,...,106.82309,2,2023-04-21 18:18:37,P00228,SMK 57,-6.290967,106.82365,13.0,2023-04-21 19:55:49,3500.0
37896,YHHK837P6Y95GN,6502902290603767,dki,Titi Siregar,M,1974,9N,Pinang Ranti - Pramuka,1.0,P00064,...,106.88116,1,2023-04-18 21:52:31,P00179,Pinang Ranti,-6.291075,106.88634,2.0,2023-04-18 22:28:22,3500.0
37897,YXPP627N4G95HO,213159426675861,emoney,drg. Zahra Nashiruddin,F,1976,1T,Cibubur - Balai Kota,1.0,B02873P,...,106.81676,12,2023-04-04 10:29:47,B00226P,Buperta Cibubur,-6.370321,106.89628,14.0,2023-04-04 13:27:25,20000.0
37898,RGVK175U2U98UV,377840859133591,emoney,Ana Agustina,M,1976,JAK.13,Tanah Abang - Jembatan Lima,1.0,B02505P,...,106.80954,33,2023-04-15 19:59:26,B01787P,JPO Blok G,-6.188861,106.81135,34.0,2023-04-15 20:27:50,0.0
37899,FMZZ963S4B68ZP,501862539795,flazz,drg. Leo Najmudin,F,1985,13,Ciledug - Tendean,0.0,P00001,...,106.74786,2,2023-04-12 21:08:12,P00106,Kebayoran Lama,-6.238340,106.77752,7.0,2023-04-12 21:34:53,3500.0

In [6]:
# Mendapatkan informasi dasar tentang data, termasuk keberadaan nilai yang hilang
data_info = df_raw.info()
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37900 entries, 0 to 37899
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transID           37900 non-null  object
 1   payCardID         37900 non-null  int64
 2   payCardBank       37900 non-null  object
 3   payCardName       37900 non-null  object
 4   payCardSex        37900 non-null  object
 5   payCardBirthDate  37900 non-null  int64
 6   corridorID        36643 non-null  object
 7   corridorName      35970 non-null  object
 8   direction         37900 non-null  float64
 9   tapInStops        36687 non-null  object
 10  tapInStopsName    37900 non-null  object
 11  tapInStopsLat     37900 non-null  float64
 12  tapInStopsLon     37900 non-null  float64
 13  stopStartSeq      37900 non-null  int64
 14  tapInTime         37900 non-null  object
 15  tapOutStops       35611 non-null  object
 16  tapOutStopsName   36556 non-null  object
 17  tapOutStopsLat    36556 non-null  float64
 18  tapOutStopsLon    36556 non-null  float64
 19  stopEndSeq        36556 non-null  float64
 20  tapOutTime        36556 non-null  object
 21  payAmount         36893 non-null  float64
dtypes: float64(7), int64(3), object(12)
memory usage: 6.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37900 entries, 0 to 37899
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transID           37900 non-null  object
 1   payCardID         37900 non-null  int64
 2   payCardBank       37900 non-null  object
 3   payCardName       37900 non-null  object
 4   payCardSex        37900 non-null  object
 5   payCardBirthDate  37900 non-null  int64
 6   corridorID        36643 non-null  object
 7   corridorName      35970 non-null  object
 8   direction         37900 non-null  float64
 9   tapInStops        36687 non-null  object
 10  tapInStopsName    37900 non-null  object
 11  tapInStopsLat     37900 non-null  float64
 12  tapInStopsLon     37900 non-null  float64
 13  stopStartSeq      37900 non-null  int64
 14  tapInTime         37900 non-null  object
 15  tapOutStops       35611 non-null  object
 16  tapOutStopsName   36556 non-null  object
 17  tapOutStopsLat    36556 non-null  float64
 18  tapOutStopsLon    36556 non-null  float64
 19  stopEndSeq        36556 non-null  float64
 20  tapOutTime        36556 non-null  object
 21  payAmount         36893 non-null  float64
dtypes: float64(7), int64(3), object(12)
memory usage: 6.4+ MB

In [7]:
# Menampilkan beberapa baris pertama dari data untuk melihat strukturnya
data_head = df_raw.head()
df_raw.head()

,transID,payCardID,payCardBank,payCardName,payCardSex,payCardBirthDate,corridorID,corridorName,direction,tapInStops,...,tapInStopsLon,stopStartSeq,tapInTime,tapOutStops,tapOutStopsName,tapOutStopsLat,tapOutStopsLon,stopEndSeq,tapOutTime,payAmount
0,EIIW227B8L34VB,180062659848800,emoney,Bajragin Usada,M,2008,5,Matraman Baru - Ancol,1.0,P00142,...,106.84402,7,2023-04-03 05:21:44,P00253,Tegalan,-6.203101,106.85715,12.0,2023-04-03 06:00:53,3500.0
1,LGXO740D2N47GZ,4885331907664776,dki,Gandi Widodo,F,1997,6C,Stasiun Tebet - Karet via Patra Kuningan,0.0,B01963P,...,106.83302,13,2023-04-03 05:42:44,B03307P,Sampoerna Strategic,-6.217152,106.81892,21.0,2023-04-03 06:40:01,3500.0
2,DJWR385V2U57TO,4996225095064169,dki,Emong Wastuti,F,1992,R1A,Pantai Maju - Kota,0.0,B00499P,...,106.81435,38,2023-04-03 05:59:06,B04962P,Simpang Kunir Kemukus,-6.133731,106.81475,39.0,2023-04-03 06:50:55,3500.0
3,JTUZ800U7C86EH,639099174703,flazz,Surya Wacana,F,1978,11D,Pulo Gebang - Pulo Gadung 2 via PIK,0.0,B05587P,...,106.93526,23,2023-04-03 05:44:51,B03090P,Raya Penggilingan,-6.183068,106.93194,29.0,2023-04-03 06:28:16,3500.0
4,VMLO535V7F95NJ,570928206772,flazz,Embuh Mardhiyah,M,1982,12,Tanjung Priok - Pluit,0.0,P00239,...,106.88900,5,2023-04-03 06:17:35,P00098,Kali Besar Barat,-6.135355,106.81143,15.0,2023-04-03 06:57:03,3500.0

In [8]:
import pandas as pd

# Mengganti dengan path lengkap ke file 'Transjakarta.csv' di sistem lokal Anda
path_file_csv_lokal = 'Transjakarta.csv'

# Membaca file CSV
df_raw = pd.read_csv(path_file_csv_lokal)

# Kolom yang relevan untuk analisis kepadatan penumpang
kolom_relevan = ['tapInTime', 'tapOutTime', 'tapInStops', 'tapOutStops', 'corridorID', 'corridorName', 'direction']

# Menyaring data hanya dengan kolom yang relevan
data_relevan = df_raw[kolom_relevan]

# Menyimpan data yang telah disaring ke file CSV baru
# Gantikan 'data_relevan.csv' dengan nama file yang Anda inginkan
data_relevan.to_csv('data_relevan.csv', index=False)